name: Workflow-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set variable global agar konsisten
env:
  # Menggunakan path absolut untuk tracking URI
  MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/mlruns"
  EXPERIMENT_NAME: "Loan Default"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client -r requirements.txt

      - name: Setup MLflow Experiment
        run: |
          # Step ini khusus untuk membuat struktur folder mlruns dan mendaftarkan experiment
          python -c "
          import mlflow
          mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}')
          mlflow.set_experiment('${{ env.EXPERIMENT_NAME }}')
          print(f'Experiment {{ env.EXPERIMENT_NAME }} created successfully at {{ env.MLFLOW_TRACKING_URI }}')
          "

      - name: Run mlflow project
        run: |
          # Passing nama experiment ke dalam mlflow run
          mlflow run MLproject --env-manager=local --experiment-name ${{ env.EXPERIMENT_NAME }}

      - name: Get latest MLflow run_id
        run: |
          # Mengambil Run ID terakhir dari experiment yang spesifik
          RUN_ID=$(python -c "
          import mlflow
          mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}')
          experiment = mlflow.get_experiment_by_name('${{ env.EXPERIMENT_NAME }}')
          runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
          print(runs.iloc[0].run_id)
          ")

          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-ci"

      # # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag workflow-ci ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
      # Upload artifact ke direktori Gdrive dengan OAuth2
      - name: Upload to Google Drive
        env:
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python upload_to_gdrive.py
